# User Configuration for ${keyboard.name}

CONFIG_ZMK_KEYBOARD_NAME="Splayt"

# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=y

# Windows battery reporting issue workaround
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Show peripheral battery. @Bravekarma said putting this in central conf is enough.
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# Enable the Bluetooth BAS (battery reporting service)
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y

# Combo settings
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=5
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=90
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=90

### Peripherals ###

## Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

## OLED  // May need to change for N!V
# CONFIG_ZMK_DISPLAY=y
# CONFIG_I2C=y
# CONFIG_SSD1306=y
# CONFIG_LV_Z_VDB_SIZE=64
# CONFIG_LV_DPI_DEF=148
# CONFIG_LV_Z_BITS_PER_PIXEL=1
# CONFIG_LV_COLOR_DEPTH_1=y
# CONFIG_MAIN_STACK_SIZE=8192
# CONFIG_ZMK_WIDGET_WPM_STATUS=y
# CONFIG_ZMK_IDLE_TIMEOUT=30000
# CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
# CONFIG_ZMK_WIDGET_LAYER_STATUS=y
# CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

## Trackball
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610=y
# CONFIG_PMW3610_SWAP_XY=y // <-- deprecated, use swap-xy; instead
# CONFIG_PMW3610_INVERT_X=y // <-- deprecated, use invert-x; instead
# CONFIG_PMW3610_INVERT_Y=y // <-- deprecated, use invert-y; instead
# CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting

## From zmk-pointing-acceleration-alpha. Enable the acceleration module.
# CONFIG_ZMK_INPUT_PROCESSOR_ACCELERATION=y

# Choose your level (1 or 2)
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_SIMPLE=y      # Level 1: Simple
# CONFIG_INPUT_PROCESSOR_ACCEL_LEVEL_STANDARD=y  # Level 2: Standard
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_GAMING_LASER=y       # Gaming laser mouse
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_OFFICE_OPTICAL=y   # Office optical mouse
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_HIGH_SENS_TRACKBALL=y # High sensitivity trackball
# CONFIG_INPUT_PROCESSOR_ACCEL_PRESET_CUSTOM=y

## @efogdev's trackball surface quality tests for pmw3610
# logs surface quality, debug level, use only for debugging because it will prevent the sensor from going to sleep
#  CONFIG_PMW3610_SQUAL_LOG=y

# surface quality log interval, msec
#  CONFIG_PMW3610_SQUAL_LOG_INTERVAL=250

# ignore first N events after boot to avoid warping
# CONFIG_PMW3610_IGNORE_FIRST_N=12

# ignore first events after rest too
# CONFIG_PMW3610_IGNORE_AFTER_REST=y